<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="26599" started-at="2021-11-30T06:32:32Z" finished-at="2021-11-30T06:32:58Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="26599" started-at="2021-11-30T06:32:32Z" finished-at="2021-11-30T06:32:58Z">
      <class name="TestScanario.TestLogin">
        <test-method status="PASS" signature="setUP()[pri:0, instance:TestScanario.TestLogin@61862a7f]" name="setUP" is-config="true" duration-ms="12990" started-at="2021-11-30T12:02:32Z" finished-at="2021-11-30T12:02:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method status="PASS" signature="Login()[pri:0, instance:TestScanario.TestLogin@61862a7f]" name="Login" duration-ms="735" started-at="2021-11-30T12:02:45Z" finished-at="2021-11-30T12:02:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:TestScanario.TestLogin@61862a7f]" name="tearDown" is-config="true" duration-ms="992" started-at="2021-11-30T12:02:45Z" finished-at="2021-11-30T12:02:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUP()[pri:0, instance:TestScanario.TestLogin@61862a7f]" name="setUP" is-config="true" duration-ms="10854" started-at="2021-11-30T12:02:46Z" finished-at="2021-11-30T12:02:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method status="FAIL" signature="LoginPageTitle()[pri:3, instance:TestScanario.TestLogin@61862a7f]" name="LoginPageTitle" duration-ms="17" started-at="2021-11-30T12:02:57Z" finished-at="2021-11-30T12:02:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Nikhil] but found [Arttha]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Nikhil] but found [Arttha]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at TestScanario.TestLogin.LoginPageTitle(TestLogin.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginPageTitle -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:TestScanario.TestLogin@61862a7f]" name="tearDown" is-config="true" duration-ms="986" started-at="2021-11-30T12:02:57Z" finished-at="2021-11-30T12:02:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestScanario.TestLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
